BOX_IMAGE = "generic/alpine313"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "master"
    #subconfig.vm.network "private_network", ip: "10.0.0.10"
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      #subconfig.vm.network "private_network", ip: "10.0.0.#{i + 10}"
    end    
  end

  config.vm.provision "shell", inline: <<-SHELL
     apk update
     apk add docker
     addgroup vagrant docker
     rc-update add docker boot
     service docker start
     apk add bash-completion
     apk add docker-bash-completion
     apk add docker-compose
  SHELL
end